.TH JSON-YAML 1 2016-04-28
.SH NAME
json-yaml \- convert JSON to YAML
.SH SYNOPSIS
.B json-yaml [OPTIONS] [FILE]
.SH DESCRIPTION
Converts JSON to YAML. Uses standard output if no filename is supplied.
.SH OPTIONS
.IP "-v, --version"
Print version number and exit.
.IP "-h, --help"
Print a help message and exit.
.SH AUTHOR
Sijmen Mulder <ik@sjmulder.nl>
