.Dd December 31, 2019
.Dt YAML-JSON 1
.Os
.Sh NAME
.Nm json-yaml
.Nd convert YAML to JSON
.Sh SYNOPSIS
.Nm
.Op Ar file
.Sh DESCRIPTION
Convert YAML to JSON.
Uses standard input if no filename is supplied.
.Sh EXAMPLES
Convert a file:
.Pp
.Dl $ yaml-json sample.yaml
.Sh SEE ALSO
.Xr json-yaml 1
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
.Sh BUGS
Aliases are not yet supported.
